apiVersion: v1
kind: Service
metadata:
  name: newlab2-service
spec:
  type: NodePort
  selector:
    app: newlab2
  ports:
    - protocol: TCP
      port: 80         # Internal cluster port
      targetPort: 80   # Port on the container
      nodePort: 30080  # The externally exposed port (must be in 30000â€“32767 range)
